# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    image: mariadb:latest
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: blablabudu
      MYSQL_DATABASE: reservation
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8180:8080
volumes:
  mysql-volume: